-- Project: A través de la historia geológica 
-- Update of contents in the DB. 

USE recorridos_geologicosdb; 

-- Recorrido Isla Bolaños 
INSERT INTO contents VALUES(19,'P1R1','../resources/travel/maps/1/Travel1.png','','image',0);
INSERT INTO contents VALUES(20,'P1R1','../resources/travel/maps/1/Travel2.jpg','','image',0);
INSERT INTO contents VALUES(21,'P1R1','../resources/travel/maps/1/Travel3.jpg','','image',0);
INSERT INTO contents VALUES(22,'P1R1','../resources/travel/maps/1/Travel4.jpg','','image',0);
INSERT INTO contents VALUES(23,'P1R1','../resources/travel/maps/1/description_point_1.txt','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus quis condimentum quam. Donec sodales rutrum lorem, quis viverra odio pharetra condimentum. Pellentesque sit amet lectus odio.','text',0);
INSERT INTO contents VALUES(24,'P3R1','../resources/travel/maps/1/Travel5.jpg','','image',0);
INSERT INTO contents VALUES(25,'P3R1','../resources/travel/maps/1/Travel6.jpg','','image',0);
INSERT INTO contents VALUES(26,'P3R1','../resources/travel/maps/1/description_point_3.txt','Pellentesque sit amet lectus odio. Duis mattis lectus eget scelerisque feugiat. Aliquam erat volutpat. Vestibulum blandit, est eget cursus mattis, ex augue dapibus tortor, vitae porta tortor ex eu eros.','text',0);
INSERT INTO contents VALUES(27,'P5R1','../resources/travel/maps/1/Travel7.jpg','','image',0);
INSERT INTO contents VALUES(28,'P5R1','../resources/travel/maps/1/Travel8.jpg','','image',0);
INSERT INTO contents VALUES(29,'P5R1','../resources/travel/maps/1/Travel9.jpg','','image',0);
INSERT INTO contents VALUES(30,'P5R1','../resources/travel/maps/1/description_point_5.txt','Aenean mollis orci enim, vitae tempus massa luctus molestie. In mattis efficitur massa non auctor. Integer placerat non mi ac rhoncus. ','text',0);
INSERT INTO contents VALUES(31,'P7R1','../resources/travel/maps/1/Travel10.jpg','','image',0);
INSERT INTO contents VALUES(32,'P7R1','../resources/travel/maps/1/Travel11.jpg','','image',0);
INSERT INTO contents VALUES(33,'P7R1','../resources/travel/maps/1/Travel12.jpg','','image',0);
INSERT INTO contents VALUES(34,'P7R1','../resources/travel/maps/1/description_point_7.txt','Integer placerat non mi ac rhoncus. Fusce condimentum, sem quis ultricies malesuada, leo tellus tincidunt ex, sed ullamcorper turpis mauris vitae magna.','text',0);
INSERT INTO contents VALUES(35,'P9R1','../resources/travel/maps/1/Travel13.jpg','','image',0);
INSERT INTO contents VALUES(36,'P9R1','../resources/travel/maps/1/Travel14.jpg','','image',0);
INSERT INTO contents VALUES(37,'P9R1','../resources/travel/maps/1/description_point_9.txt','Phasellus semper lorem vitae nisi ultrices, non interdum ligula vehicula. Curabitur justo lorem, consequat at ornare vitae, dignissim in augue. ','text',0);
INSERT INTO contents VALUES(38,'P9R1','https://www.youtube.com/watch?v=ekrrQk-axFE','','video',0);
INSERT INTO contents VALUES(39,'P9R1','https://www.youtube.com/watch?v=tS5jzLqhCzI','','video',0);
INSERT INTO contents VALUES(40,'P11R1','../resources/travel/maps/1/Travel15.jpg','','image',0);
INSERT INTO contents VALUES(41,'P11R1','../resources/travel/maps/1/Travel16.jpg','','image',0);
INSERT INTO contents VALUES(42,'P11R1','../resources/travel/maps/1/Travel17.jpg','','image',0);
INSERT INTO contents VALUES(43,'P11R1','../resources/travel/maps/1/Travel18.jpg','','image',0);
INSERT INTO contents VALUES(44,'P11R1','../resources/travel/maps/1/description_point_11.txt','In felis elit, finibus id pharetra id, elementum at sapien. Mauris non risus tincidunt, interdum eros a, semper felis. Pellentesque eu enim viverra, cursus ex non, venenatis nulla.','text',0);
INSERT INTO contents VALUES(45,'P14R1','../resources/travel/maps/1/Travel19.jpg','','image',0);
INSERT INTO contents VALUES(46,'P14R1','../resources/travel/maps/1/description_point_14.txt','Duis arcu eros, imperdiet a nisl at, elementum imperdiet ipsum. Curabitur tincidunt malesuada urna sit amet vestibulum. Morbi sollicitudin pulvinar urna, viverra cursus nunc dignissim quis.','text',0);
INSERT INTO contents VALUES(47,'P16R1','../resources/travel/maps/1/Travel20.jpg','','image',0);
INSERT INTO contents VALUES(48,'P16R1','../resources/travel/maps/1/Travel21.jpg','','image',0);
INSERT INTO contents VALUES(49,'P16R1','../resources/travel/maps/1/Travel22.jpg','','image',0);
INSERT INTO contents VALUES(50,'P16R1','../resources/travel/maps/1/description_point_16.txt','Etiam a rhoncus velit. Pellentesque pharetra pharetra arcu, a interdum ex varius non. Duis pulvinar non ante id tincidunt.','text',0);
INSERT INTO contents VALUES(51,'P20R1','../resources/travel/maps/1/Travel23.jpg','','image',0);
INSERT INTO contents VALUES(52,'P20R1','../resources/travel/maps/1/Travel24.jpg','','image',0);
INSERT INTO contents VALUES(53,'P20R1','../resources/travel/maps/1/Travel25.jpg','','image',0);
INSERT INTO contents VALUES(54,'P20R1','../resources/travel/maps/1/Travel26.jpg','','image',0);
INSERT INTO contents VALUES(55,'P20R1','../resources/travel/maps/1/description_point_20.txt','Proin feugiat blandit eros, eu venenatis ligula euismod et. Phasellus gravida auctor dui et gravida. Duis facilisis justo eu erat tempus pretium','text',0);
INSERT INTO contents VALUES(56,'P20R1','https://www.youtube.com/watch?v=8uqU6psFyv4','','video',0);
INSERT INTO contents VALUES(57,'P22R1','../resources/travel/maps/1/Travel27.jpg','','image',0);
INSERT INTO contents VALUES(58,'P22R1','../resources/travel/maps/1/Travel28.jpg','','image',0);
INSERT INTO contents VALUES(59,'P22R1','../resources/travel/maps/1/Travel29.jpg','','image',0);
INSERT INTO contents VALUES(60,'P22R1','../resources/travel/maps/1/description_point_22.txt','Ut ut bibendum nisi. Suspendisse a convallis lorem, et scelerisque risus. Ut hendrerit dolor quis libero auctor dignissim.','text',0);

-- Recorrido Isla Murcielago 
INSERT INTO contents VALUES(61,'P1R2','../resources/travel/maps/2/Travel1.png','','image',0);
INSERT INTO contents VALUES(62,'P1R2','../resources/travel/maps/2/Travel2.png','','image',0);
INSERT INTO contents VALUES(63,'P1R2','../resources/travel/maps/2/Travel3.png','','image',0);
INSERT INTO contents VALUES(64,'P1R2','../resources/travel/maps/2/description_point_1.txt','Vestibulum sed ex at sem posuere bibendum. Vivamus cursus convallis nunc ut porttitor. In placerat lorem ut nibh iaculis luctus. Proin lacinia justo sed nisi sollicitudin, at rutrum libero porttitor.','text',0);
INSERT INTO contents VALUES(65,'P3R2','../resources/travel/maps/2/Travel4.png','','image',0);
INSERT INTO contents VALUES(66,'P3R2','../resources/travel/maps/2/Travel5.png','','image',0);
INSERT INTO contents VALUES(67,'P3R2','../resources/travel/maps/2/Travel6.png','','image',0);
INSERT INTO contents VALUES(68,'P3R2','../resources/travel/maps/2/description_point_3.txt','Duis id gravida neque. Sed tristique sollicitudin vulputate. Nulla tempus tellus nisi, eu vestibulum turpis gravida a. Maecenas sodales condimentum lorem, tincidunt commodo ante vulputate ut.','text',0);
INSERT INTO contents VALUES(69,'P3R2','https://www.youtube.com/watch?v=ltJuwoGe5BA','','video',0);
INSERT INTO contents VALUES(70,'P3R2','https://www.youtube.com/watch?v=JMguEHXP0sc','','video',0);
INSERT INTO contents VALUES(71,'P4R2','../resources/travel/maps/2/Travel7.png','','image',0);
INSERT INTO contents VALUES(72,'P4R2','../resources/travel/maps/2/Travel8.png','','image',0);
INSERT INTO contents VALUES(73,'P4R2','../resources/travel/maps/2/description_point_4.txt','Duis sed semper massa. Nunc ex nibh, aliquam nec tortor eget, consequat consequat urna. Vestibulum eget elit facilisis, venenatis sem vitae, laoreet ipsum.','text',0);
INSERT INTO contents VALUES(74,'P5R2','../resources/travel/maps/2/Travel9.png','','image',0);
INSERT INTO contents VALUES(75,'P5R2','../resources/travel/maps/2/Travel10.png','','image',0);
INSERT INTO contents VALUES(76,'P5R2','../resources/travel/maps/2/Travel11.png','','image',0);
INSERT INTO contents VALUES(77,'P5R2','../resources/travel/maps/2/description_point_5.txt','Morbi sodales risus vitae tortor pretium pulvinar. Morbi volutpat dapibus dignissim. Nulla consequat varius ante, quis mattis massa facilisis non. Nunc in consequat ligula. Morbi tempus varius tempor.','text',0);
INSERT INTO contents VALUES(78,'P8R2','../resources/travel/maps/2/Travel12.png','','image',0);
INSERT INTO contents VALUES(79,'P8R2','../resources/travel/maps/2/Travel13.png','','image',0);
INSERT INTO contents VALUES(80,'P8R2','../resources/travel/maps/2/description_point_8.txt','Morbi lobortis aliquam ipsum in rhoncus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam ligula leo, tristique quis justo vel, pellentesque finibus justo.','text',0);
INSERT INTO contents VALUES(81,'P11R2','../resources/travel/maps/2/Travel14.png','','image',0);
INSERT INTO contents VALUES(82,'P11R2','../resources/travel/maps/2/Travel15.png','','image',0);
INSERT INTO contents VALUES(83,'P11R2','../resources/travel/maps/2/Travel16.png','','image',0);
INSERT INTO contents VALUES(84,'P11R2','../resources/travel/maps/2/description_point_11.txt','Ut dapibus nibh in hendrerit lacinia. Mauris lacinia faucibus libero. Quisque ullamcorper commodo neque, eu placerat metus. Vestibulum dignissim hendrerit arcu vel tincidunt.','text',0);
INSERT INTO contents VALUES(85,'P11R2','https://www.youtube.com/watch?v=6TyIiw3ByuE','','video',0);
INSERT INTO contents VALUES(86,'P14R2','../resources/travel/maps/2/Travel17.png','','image',0);
INSERT INTO contents VALUES(87,'P14R2','../resources/travel/maps/2/Travel18.png','','image',0);
INSERT INTO contents VALUES(88,'P14R2','../resources/travel/maps/2/Travel19.png','','image',0);
INSERT INTO contents VALUES(89,'P14R2','../resources/travel/maps/2/Travel20.png','','image',0);
INSERT INTO contents VALUES(90,'P14R2','../resources/travel/maps/2/Travel21.png','','image',0);
INSERT INTO contents VALUES(91,'P14R2','../resources/travel/maps/2/description_point_14.txt','Donec posuere finibus massa. Aliquam consequat massa non massa mattis, eget iaculis ante ultrices. Praesent ultrices mi felis. ','text',0);
INSERT INTO contents VALUES(92,'P16R2','../resources/travel/maps/2/Travel22.png','','image',0);
INSERT INTO contents VALUES(93,'P16R2','../resources/travel/maps/2/Travel23.png','','image',0);
INSERT INTO contents VALUES(94,'P16R2','../resources/travel/maps/2/Travel24.png','','image',0);
INSERT INTO contents VALUES(95,'P16R2','../resources/travel/maps/2/description_point_16.txt','Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi sit amet interdum ex.','text',0);
INSERT INTO contents VALUES(96,'P20R2','../resources/travel/maps/2/Travel25.png','','image',0);
INSERT INTO contents VALUES(97,'P20R2','../resources/travel/maps/2/description_point_20.txt','Ut ipsum diam, eleifend ac nulla vel, varius porttitor neque. Donec nunc turpis, posuere viverra tempor ut, euismod eget eros. Morbi porttitor velit quis placerat lacinia.','text',0);
INSERT INTO contents VALUES(98,'P21R2','../resources/travel/maps/2/Travel26.png','','image',0);
INSERT INTO contents VALUES(99,'P21R2','../resources/travel/maps/2/Travel27.png','','image',0);
INSERT INTO contents VALUES(100,'P21R2','../resources/travel/maps/2/Travel28.png','','image',0);
INSERT INTO contents VALUES(101,'P21R2','../resources/travel/maps/2/Travel29.png','','image',0);
INSERT INTO contents VALUES(102,'P21R2','../resources/travel/maps/2/Travel30.png','','image',0);
INSERT INTO contents VALUES(103,'P21R2','../resources/travel/maps/2/description_point_21.txt','Nam eleifend et felis sit amet facilisis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque nec urna et eros scelerisque consectetur non nec neque.','text',0);
